---
- hosts: localhost
  become: true
  tasks:
    - name: Check if VM directory exists
      stat:
        path: "/virt/vms/{{ vmname }}"
      register: vm_exists

    - name: destroy VM
      virt:
        name: "{{ vmname }}"
        command: destroy
        uri : "qemu:///session"

    - name: Undefine VM
      virt:
        name: "{{ vmname }}"
        command: undefine
        uri : "qemu:///session"
      
    - name: Remove VM directory
      file:
        path: "/virt/vms/{{ vmname }}"
        state: absent
